### ISSUE TITLE
X-Plattform Docker Image + Build Error on ARM

### ISSUE THREAD

**Issue by z-master42** [unfoldedcircle/integration-home-assistant#27]
Is it possible to provide an X-platform Docker image so that the ARM platform can also be used?

The whole thing would be best as an addon for Home Assistant.

I still tried to build it for ARM and now have the following error message:

```
error[E0061]: this function takes 4 arguments but 5 arguments were supplied
   --> src/main.rs:187:21
    |
187 |       if let Err(e) = publish_service(
    |                       ^^^^^^^^^^^^^^^
...
191 |           "uc-integration",
    |  _________________________-
192 | |         "tcp",
    | |         -----
    | |_________|___|
    |           |   help: remove the extra argument
    |           unexpected argument of type `&'static str`
    |
note: function defined here
   --> src/server/mod.rs:24:8
    |
24  | pub fn publish_service(
    |        ^^^^^^^^^^^^^^^
25  |     _instance_name: impl AsRef<str>,
    |     -------------------------------
26  |     _reg_type: impl Into<String>,
    |     ----------------------------
27  |     _port: u16,
    |     ----------
28  |     _txt: Vec<String>,
    |     -----------------

For more information about this error, try `rustc --explain E0061`.
error: could not compile `uc-intg-hass` (bin "uc-intg-hass") due to previous error
```

**Comment by zehnm** [comment]
This build error has been fixed by commit https://github.com/unfoldedcircle/integration-home-assistant/commit/617466d8098c6bcb7577ebded32736531ee9667c which is not yet included in a release tag.

Please try to build from the main branch.

**Comment by z-master42** [comment]
Okay, thank you.
But I also think I have fundamentally misunderstood something here. For me, it read that in order to use Home Assistant via Remote Two, I have to have the integration running on a separate device, but this is not the case.

**Comment by zehnm** [comment]
True, this integration is included on the device :-)
As long as you are not a developer, or require multiple Home Assistant servers, you don't have to run this integration.
