### ISSUE TITLE
Add Scene support

### ISSUE THREAD

**Issue by pvmil** [unfoldedcircle/integration-home-assistant#29]
Would it be possible to add support for scene's ?
(HA developer documentation: https://developers.home-assistant.io/docs/core/entity/scene?_highlight=sc)

This would enable to set my lights to a specific scene in HA
(Workaround: add script which sets scene)

**Comment by zehnm** [comment]
If I understand HA scenes correctly, that should be very simple to implement with a push button. Scenes have no state and can only be activated, perfect for a push button entity in Remote Two :-)
@pvmil or do I miss something?

**Comment by pvmil** [comment]
You are right, it would be nice to make this work without additional steps. No super high prio

**Comment by zehnm** [comment]
Already working :-) Tested with the auto-generated Philips Hue bridge scenes.
It will be included in the next firmware release if I don't find any showstoppers.
